# NumPy Array Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
arr[1:5]

array([2, 3, 4, 5])

In [4]:
arr[4:]

array([5, 6, 7])

In [5]:
arr[:4]

array([1, 2, 3, 4])

### Negative Slicing

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[-3:-1]

array([5, 6])

### Step

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
arr[1:5:2]

array([2, 4])

In [10]:
arr[::2]

array([1, 3, 5, 7])

### Slicing 2-D Arrays

In [11]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
arr1[1, 1:5]

array([ 7,  8,  9, 10])

In [13]:
arr1[0:2, 2]

array([3, 8])

In [14]:
arr1[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

#### Ellipsis can also be used along with basic slicing. Ellipsis (…) is the number of : objects needed to make a selection tuple of the same length as the dimensions of the array.

In [15]:
arr = np.array([[[1, 2, 3],[4, 5, 6]],
                [[7, 8, 9],[10, 11, 12]]])
 
print(arr[...,1]) # Equivalent to arr[: ,: ,1 ]

[[ 2  5]
 [ 8 11]]
