# NumPy Data Types
Below is a list of all data types in NumPy and the characters used to represent them:

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [1]:
import numpy as np

### Checking the Data Type of an Array

In [2]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [3]:
arr1 = np.array(['apple', 'banana', 'cherry'])
arr1.dtype

dtype('<U6')

### Creating Arrays With a Defined Data Type

In [4]:
arr2 = np.array([1,2,3,4], dtype='S')
arr2

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [5]:
arr2.dtype

dtype('S1')

For i, u, f, S and U we can define size as well.

In [6]:
arr3 = np.array([1, 2, 3, 4], dtype='i4')

print(arr3)
print(arr3.dtype)

[1 2 3 4]
int32


### Converting Data Type on Existing Arrays

In [7]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
newarr1 = arr.astype(int)

print(newarr, newarr.dtype)
print(newarr1, newarr1.dtype)

[1 2 3] int32
[1 2 3] int32


In [8]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
