In [1]:
import numpy as np

### String Operations

In [2]:
print(np.char.lower('GEEKS'))

print(np.char.lower(['GEEKS', 'FOR']))

geeks
['geeks' 'for']


In [3]:
print(np.char.split('geeks for geeks'))

print(np.char.split('geeks, for, geeks', sep = ','))

['geeks', 'for', 'geeks']
['geeks', ' for', ' geeks']


In [4]:
print(np.char.join('-', 'geeks'))

print(np.char.join(['-', ':'], ['geeks', 'for']))

g-e-e-k-s
['g-e-e-k-s' 'f:o:r']


### String Information

In [5]:
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.count(a,'geek'))
 
# counting a substring
print(np.char.count(a, 'fo'))

[1 0 1]
[0 1 0]


In [6]:
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.rfind(a,'geek'))
 
# counting a substring
print(np.char.rfind(a, 'fo'))

[ 0 -1  0]
[-1  0 -1]


In [8]:
print(np.char.isnumeric('geeks'))

print(np.char.isnumeric('12geeks'))

False
False


### String Comparison

In [9]:
a=np.char.equal('geeks','for')
 
print(a)

False


In [11]:
a=np.char.not_equal('geeks','for')

print(a)

True


In [12]:
a=np.char.greater('geeks','for')
 
print(a)

True
