In [1]:
import numpy as np

## rank, determinant, trace, etc. of an array/matrix

In [2]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


## Matrix eigenvalues Functions

In [3]:
a = np.array([[1, -2j], [2j, 5]])
 
print("Array is :\n",a)
 
# calculating an eigen value using eigh() function
c, d = np.linalg.eigh(a)
 
print("\nEigen value is :", c)
print("\nCorresponding eigenvectors (in columns) is :\n", d)

Array is :
 [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]

Eigen value is : [0.17157288 5.82842712]

Corresponding eigenvectors (in columns) is :
 [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [4]:
a = np.diag((1, 2, 3))
 
print("Array is :\n",a)
 
# calculating an eigen value using eigh() function
c, d = np.linalg.eigh(a)
 
print("\nEigen value is :", c)
print("\nCorresponding eigenvectors (in columns) is :\n", d)

Array is :
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Eigen value is : [1. 2. 3.]

Corresponding eigenvectors (in columns) is :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Matrix and vector products

In [5]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [2,8,0]])

dot_matrix = np.dot(a,b.transpose())
print("Dot product of matrix 'a' and 'b' is:\n", dot_matrix)

cross_matrix = np.cross(a,b)
print("\nCross product of matrix 'a' and 'b' is:\n", cross_matrix)

Dot product of matrix 'a' and 'b' is:
 [[ 50  18]
 [122  48]]

Cross product of matrix 'a' and 'b' is:
 [[ -6  12  -6]
 [-48  12  22]]


In [6]:
# Scalars
product = np.dot(5, 4)
print("Dot Product of scalar values  : ", product)
 
# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = np.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product of scalar values  :  20
Dot Product  :  (-7+22j)


In [7]:
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = np.vdot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product  :  (23-2j)


## Solving equations and inverting matrices

In [8]:
a = np.array([[1, 2], [3, 4]])

b = np.array([8, 18])
 
print("Solution of linear equations:", np.linalg.solve(a, b))

Solution of linear equations: [2. 3.]
