In [1]:
import numpy as np

# Sorting

### numpy.sort() : This function returns a sorted copy of an array.

In [2]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [3]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [4]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [12]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [9]:
a = np.array([[3, 2, 4], [5, 0, 1]])

# sort along the first axis
arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)        
 
 
# sort along the last axis
arr2 = np.sort(a, axis = -1)        
print ("\nAlong last axis : \n", arr2)

arr1 = np.sort(a, axis = None)        
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[3 0 1]
 [5 2 4]]

Along last axis : 
 [[2 3 4]
 [0 1 5]]

Along none axis : 
 [0 1 2 3 4 5]


### numpy.argsort() : This function returns the indices that would sort an array.

In [13]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
print('Original array:\n', a)

b = np.argsort(a)
print('Sorted indices of original array->', b)
 
# To get sorted array using sorted indices c is temp array created of same len as of b
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
print('Sorted array->', c)

Original array:
 [9 3 1 7 4 3 6]
Sorted indices of original array-> [2 1 5 4 6 3 0]
Sorted array-> [1 3 3 4 6 7 9]


### numpy.lexsort() : This function returns an indirect stable sort using a sequence of keys.

In [17]:
# First column
a = np.array([9, 3, 1, 3, 4, 3, 6])
 
# Second column 
b = np.array([4, 6, 9, 2, 1, 8, 7]) 
print('column a, column b')
for (i, j) in zip(a, b):
    print(i, '        ', j)
 
# Sort by a then by b
ind = np.lexsort((b, a)) 
print('Sorted indices->', ind)

column a, column b
9          4
3          6
1          9
3          2
4          1
3          8
6          7
Sorted indices-> [2 3 1 5 4 6 0]


# Searching

### where() method

In [18]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


### searchsorted(): performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [20]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [21]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [22]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


### numpy.argmax() : This function returns indices of the max element of the array in a particular axis.

In [24]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
 
# No axis mentioned, so works on entire array
print("\nMax element : ", np.argmax(array))
 
# returning Indices of the max element as per the indices
print("\nIndices of Max element : ", np.argmax(array, axis=0))
print("\nIndices of Max element : ", np.argmax(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11

Indices of Max element :  [2 2 2 2]

Indices of Max element :  [3 3 3]


### numpy.argmin() : This function returns the indices of the minimum values along an axis.

In [25]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
 
# No axis mentioned, so works on entire array
print("\nMax element : ", np.argmin(array))
 
# returning Indices of the max element as per the indices
print("\nIndices of Max element : ", np.argmin(array, axis=0))
print("\nIndices of Max element : ", np.argmin(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  0

Indices of Max element :  [0 0 0 0]

Indices of Max element :  [0 0 0]


# Counting

### numpy.count_nonzero() : Counts the number of non-zero values in the array .

In [27]:
a = np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]])
b = np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]], axis=0)
 
print("Number of nonzero values is :",a)
print("Number of nonzero values is :",b)

Number of nonzero values is : 5
Number of nonzero values is : [1 1 1 1 1]
