In [1]:
from numpy import random

## Generate Random Number

In [2]:
x = random.randint(100)

print(x)

72


## Generate Random Float

In [3]:
x = random.rand()

print(x)

0.8864042268094877


In [4]:
out_val = random.random_sample()
print ("Output random float value : ", out_val) 

Output random float value :  0.3428497417388606


In [5]:
out_val = random.ranf()
print ("Output random float value : ", out_val)

Output random float value :  0.6634973100680018


## Generate Random Array

In [6]:
x=random.randint(100, size=(5))

print(x)

[60 46 34 86 58]


In [7]:
out_arr = random.randint(low = 0, high = 3, size = 5)
print ("Output 1D Array filled with random integers : ", out_arr) 

Output 1D Array filled with random integers :  [1 1 0 0 0]


In [8]:
x = random.randint(100, size=(3, 5))

print(x)

[[38  3 42 77 61]
 [67 16 79 16 19]
 [80 72 30 21 70]]


In [9]:
out_arr = random.randint(low = 4, size =(2, 3))
print ("Output 2D Array filled with random integers :\n", out_arr) 

Output 2D Array filled with random integers :
 [[0 1 2]
 [0 1 3]]


In [10]:
out_arr = random.randint(2, 10, (2, 3, 4))
print ("Output 3D Array filled with random integers :\n", out_arr) 

Output 3D Array filled with random integers :
 [[[2 5 5 2]
  [9 7 3 7]
  [3 5 2 6]]

 [[2 4 6 8]
  [2 6 8 2]
  [3 6 3 7]]]


In [11]:
x = random.rand(5)

print(x)

[0.56626707 0.80797591 0.2393135  0.7748306  0.13390687]


In [12]:
x = random.rand(3, 5)

print(x)

[[0.48591899 0.12245356 0.49043478 0.18122636 0.79242375]
 [0.37626187 0.83060112 0.07549712 0.71308729 0.46901696]
 [0.80264731 0.02834045 0.67316114 0.61295262 0.2156503 ]]


In [13]:
out_arr = random.random_sample(size =(1, 3))
print ("Output 2D Array filled with random floats : ", out_arr)

Output 2D Array filled with random floats :  [[0.12032153 0.97238984 0.41175643]]


In [14]:
out_arr = random.random_sample((3, 2, 1))
print ("Output 3D Array filled with random floats :\n", out_arr)

Output 3D Array filled with random floats :
 [[[0.08902181]
  [0.8523623 ]]

 [[0.87812637]
  [0.24805779]]

 [[0.56724427]
  [0.50359232]]]


In [15]:
out_arr = random.ranf(size =(2, 1))
print ("Output 2D Array filled with random floats :\n", out_arr)

Output 2D Array filled with random floats :
 [[0.85338229]
 [0.84522152]]


In [16]:
out_arr = random.ranf((3, 3, 2))
print ("Output 3D Array filled with random floats :\n", out_arr)

Output 3D Array filled with random floats :
 [[[0.53470713 0.10986793]
  [0.40308941 0.96457214]
  [0.52157974 0.38210933]]

 [[0.7535996  0.30249772]
  [0.30073639 0.95502557]
  [0.44072798 0.47617746]]

 [[0.12477983 0.52373613]
  [0.11870362 0.96940585]
  [0.73163262 0.25261296]]]


## Generate Random Number From Array

In [17]:
x = random.choice([3, 5, 7, 9])

print(x)

7


In [18]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 5 7 9]
 [3 9 7 9 7]
 [3 9 5 7 3]]
