# Why use ufuncs?
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where - boolean array or condition defining where the operations should take place.

dtype - defining the return type of elements.

out - output array where the return value should be copied.

In [1]:
import numpy as np

## Create Your Own ufunc
The frompyfunc() method takes the following arguments:

function - the name of the function.

inputs - the number of input arguments (arrays).

outputs - the number of output arrays.

In [2]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [3]:
print(type(myadd))

<class 'numpy.ufunc'>


## Simple Arithmetic

In [4]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [5]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [6]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [7]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [8]:
in_num = 2.0
print ("Input  number : ", in_num)
 
out_num = np.reciprocal(in_num)
print ("Output number : ", out_num)

Input  number :  2.0
Output number :  0.5


In [9]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
newarr1 = np.remainder(arr1, arr2)

print(newarr)
print(newarr1)

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [12]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


## Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

truncation, fix, rounding, floor, ceil

In [13]:
lst = [-3.1666, 3.6667]

arr1 = np.trunc(lst)
arr2 = np.fix(lst)
arr3 = np.around(lst, 2)
arr4 = np.floor(lst)
arr5 = np.ceil(lst)

print(arr1, arr2, arr3, arr4, arr5)

[-3.  3.] [-3.  3.] [-3.17  3.67] [-4.  3.] [-3.  4.]


In [14]:
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


## Exponents and logarithms Functions

In [15]:
in_array = [1, 3, 5]
print ("Input array : ", in_array)
 
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


In [16]:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [17]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [18]:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


### Log at Any Base

In [19]:
from math import log

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


## Summations
Addition is done between two arguments whereas summation happens over n elements.

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [22]:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


## Products

In [23]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [24]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [25]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [26]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


## Differences
A discrete difference means subtracting two successive elements.

In [27]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [28]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


## Finding LCM (Lowest Common Multiple)

In [29]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [30]:
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [31]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


## Finding GCD (Greatest Common Denominator)

In [32]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [33]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


## Trigonometric Functions

In [34]:
# create an array of angles
angles = np.array([0, 30, 45, 60, 90, 180])

# conversion of degree into radians using deg2rad function
radians = np.deg2rad(angles)

# sine of angles
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(sine_value)

# inverse sine of sine values
print('\nInverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))

# hyperbolic sine of angles
print('\nSine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(sineh_value)

# inverse sine hyperbolic
print('\nInverse Sine hyperbolic:')
print(np.rad2deg(np.arcsinh(sineh_value)))

# hypot function demonstration
base = 4
height = 3
print('\nhypotenuse of right triangle is:')
print(np.hypot(base, height))

Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]

Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]

Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]

Inverse Sine hyperbolic:
[  0.  30.  45.  60.  90. 180.]

hypotenuse of right triangle is:
5.0


## Complex number Function

In [35]:
print("Is Real : ", np.isreal([1+1j, 0j]), "\n")
 
print("Is Real : ", np.isreal([1, 0]), "\n")

Is Real :  [False  True] 

Is Real :  [ True  True] 



In [36]:
in_complx1 = 2+4j
out_complx1 = np.conj(in_complx1)
print ("Output conjugated complex number of  2+4j : ", out_complx1)
 
in_complx2 =5-8j
out_complx2 = np.conj(in_complx2)
print ("Output conjugated complex number of 5-8j: ", out_complx2)

Output conjugated complex number of  2+4j :  (2-4j)
Output conjugated complex number of 5-8j:  (5+8j)


## Set Operations

In [37]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [38]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [39]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [40]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [41]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


## Statistical functions

In [42]:
# construct a weight array
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# minimum and maximum
print('Minimum and maximum weight of the students: ')
print(np.amin(weight), np.amax(weight))

# range of weight i.e. max weight-min weight
print('\nRange of the weight of the students: ')
print(np.ptp(weight))

# percentile
print('\nWeight below which 70 % student fall: ')
print(np.percentile(weight, 70))

# mean
print('\nMean weight of the students: ')
print(np.mean(weight))

# median
print('\nMedian weight of the students: ')
print(np.median(weight))

# standard deviation
print('\nStandard deviation of weight of the students: ')
print(np.std(weight))

# variance
print('\nVariance of weight of the students: ')
print(np.var(weight))

# average
print('\nAverage weight of the students: ')
print(np.average(weight))

Minimum and maximum weight of the students: 
45.0 73.25

Range of the weight of the students: 
28.25

Weight below which 70 % student fall: 
55.317

Mean weight of the students: 
54.3225

Median weight of the students: 
51.6

Standard deviation of weight of the students: 
8.052773978574091

Variance of weight of the students: 
64.84716875

Average weight of the students: 
54.3225


## Special functions

In [43]:
arr1 = [1, 27000, 64, -1000]
print ("cbrt Value of arr1 : \n", np.cbrt(arr1))
  
arr2 = [1024 ,-128]
print ("\ncbrt Value of arr2 : ", np.cbrt(arr2))

cbrt Value of arr1 : 
 [  1.  30.   4. -10.]

cbrt Value of arr2 :  [10.0793684 -5.0396842]


In [44]:
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ]
print ("Input array : ", in_array)
 
out_array = np.clip(in_array, a_min = 2, a_max = 6)
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]
