In [1]:
import numpy as np

### Checking NumPy Version

In [2]:
np.__version__

'1.21.2'

### Creating Arrays

In [3]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
arr = np.array([1, 2, 3, 4, 5])  # from list
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
arr1 = np.array((1, 2, 3, 4, 5))  # from tuple
print(arr1)

[1 2 3 4 5]


In [6]:
a = np.array(42)  # 0-D Array
b = np.array([1, 2, 3, 4, 5])  # 1-D Array
c = np.array([[1, 2, 3], [4, 5, 6]])  # 2-D Array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 3-D Array

print(f"\na = {a}\nDimension of a: {a.ndim}")
print(f"\nb = {b}\nDimension of b: {b.ndim}")
print(f"\nc = {c}\nDimension of c: {c.ndim}")
print(f"\nd = {d}\nDimension of d: {d.ndim}")


a = 42
Dimension of a: 0

b = [1 2 3 4 5]
Dimension of b: 1

c = [[1 2 3]
 [4 5 6]]
Dimension of c: 2

d = [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension of d: 3


In [7]:
e = np.array([1, 2, 3, 4, 5], ndmin=5)  # 5-D Array
print(f"\ne = {e}\nDimension of e: {e.ndim}")


e = [[[[[1 2 3 4 5]]]]]
Dimension of e: 5
