In [1]:
import numpy as np

# Shape of an Array

In [3]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1.shape

(2, 4)

In [6]:
arr2 = np.array([1, 2, 3, 4], ndmin=5)

print(arr2)
print('shape of array :', arr2.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

In [7]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
newarr = arr3.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
newarr = arr3.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Returns view not copy

In [11]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr4.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


#### Unknown Dimension

In [12]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr5.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Flattening the arrays

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
