In [1]:
import numpy as np

# NumPy Joining Array

### Joining Arrays Using Concatenate Function
If axis is not explicitly passed, it is taken as 0.

In [2]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [3]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions
If axis is not explicitly passed, it is taken as 0.

In [5]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Stacking Along Rows

In [7]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns

In [8]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)

In [9]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

In [10]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [12]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0], '\n')
print(newarr[1], '\n')
print(newarr[2], '\n')

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]
 [11 12]] 



In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr[0], '\n')
print(newarr[1], '\n')
print(newarr[2], '\n')

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]] 

[[13 14 15]
 [16 17 18]] 



In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr[0], '\n')
print(newarr[1], '\n')
print(newarr[2], '\n')

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]] 

[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]] 

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]] 



In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr[0], '\n')
print(newarr[1], '\n')
print(newarr[2], '\n')

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]] 

[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]] 

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]] 



In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr[0], '\n')
print(newarr[1], '\n')
print(newarr[2], '\n')

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]] 

[[13 14 15]
 [16 17 18]] 

