In [1]:
import numpy as np

# Iterating Arrays

In [2]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using nditer()

In [7]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [12]:
arr = np.arange(12)
arr = arr.reshape(3,4)

print(arr, '\n')

for x in np.nditer(arr):
    print(x, end=' ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

0 1 2 3 4 5 6 7 8 9 10 11 

#### The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering. This can be seen by iterating over the transpose of the above array.

In [13]:
arr = np.arange(12)
arr = arr.reshape(3,4)
arr = arr.T

print(arr, '\n')

for x in np.nditer(arr):
    print(x, end=' ')

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

0 1 2 3 4 5 6 7 8 9 10 11 

### Controlling Iteration Order:

In [14]:
arr = np.arange(12)
arr = arr.reshape(3,4)

print(arr, '\n')

for x in np.nditer(arr, order='F'):
    print(x, end=' ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

0 4 8 1 5 9 2 6 10 3 7 11 

### Modifying Array Values:

In [18]:
arr = np.arange(12)
arr = arr.reshape(4,3)

print(arr, '\n')

for x in np.nditer(arr, op_flags=['readwrite']):
    x[...] = 5*x

print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]


### Iterating Array With Different Data Types:

In [8]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


### Iterating With Different Step Size:

In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


### Broadcasting Iteration:
If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently.

In [19]:
arr1 = np.arange(12)
arr1 = arr1.reshape(3,4) 
print(arr1, '\n')  
 
arr2 = np.array([5, 6, 7, 8], dtype = int)  
print(arr2, '\n')
 
print('Modified array is:')
for x,y in np.nditer([arr1,arr2]): 
    print("%d:%d" % (x,y))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[5 6 7 8] 

Modified array is:
0:5
1:6
2:7
3:8
4:5
5:6
6:7
7:8
8:5
9:6
10:7
11:8


## Enumerated Iteration Using ndenumerate()

In [10]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
