In [1]:
import numpy as np

### bitwise_and() function

In [2]:
num1 = 10
num2 = 11

out_num = np.bitwise_and(num1, num2)

print("bitwise_and of 10 and 11 : ", out_num)

bitwise_and of 10 and 11 :  10


In [17]:
arr1 = [2, 8, 125]
arr2 = [3, 3, 115]

out_arr = np.bitwise_and(arr1, arr2) 
print("Output array after bitwise_and: ", out_arr)

Output array after bitwise_and:  [  2   0 113]


### bitwise_or() function

In [8]:
num1 = 10
num2 = 11

out_num = np.bitwise_or(num1, num2)

print("bitwise_or of 10 and 11 : ", out_num)

bitwise_or of 10 and 11 :  11


In [16]:
arr1 = [2, 8, 125]
arr2 = [3, 3, 115]

out_arr = np.bitwise_or(arr1, arr2) 
print("Output array after bitwise_or: ", out_arr)

Output array after bitwise_or:  [  3  11 127]


### bitwise_xor() function

In [10]:
num1 = 10
num2 = 11

out_num = np.bitwise_xor(num1, num2)

print("bitwise_xor of 10 and 11 : ", out_num)

bitwise_xor of 10 and 11 :  1


In [15]:
arr1 = [2, 8, 125]
arr2 = [3, 3, 115]

out_arr = np.bitwise_xor(arr1, arr2) 
print("Output array after bitwise_xor: ", out_arr)

Output array after bitwise_xor:  [ 1 11 14]


### invert() function

In [14]:
num = 10

out_num = np.invert(num) 
print("inversion of 10 : ", out_num) 

inversion of 10 :  -11


In [13]:
arr = [2, 0, 25]
   
out_arr = np.invert(arr) 
print("Output array after inversion: ", out_arr)

Output array after inversion:  [ -3  -1 -26]


### left_shift() function

In [18]:
in_num = 5
bit_shift = 2
 
print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift ) 
   
out_num = np.left_shift(in_num, bit_shift) 
print ("After left shifting 2 bit  : ", out_num) 

Input  number :  5
Number of bit shift :  2
After left shifting 2 bit  :  20


In [20]:
in_arr = [2, 8, 15]
bit_shift =[3, 4, 5]
  
print ("Input array : ", in_arr) 
print ("Number of bit shift : ", bit_shift)
   
out_arr = np.left_shift(in_arr, bit_shift) 
print ("Output array after left shifting: ", out_arr) 

Input array :  [2, 8, 15]
Number of bit shift :  [3, 4, 5]
Output array after left shifting:  [ 16 128 480]


### right_shift() function

In [22]:
in_num = 20
bit_shift = 2

print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift )

out_num = np.right_shift(in_num, bit_shift)

print ("After right shifting 2 bit  : ", out_num)

Input  number :  20
Number of bit shift :  2
After right shifting 2 bit  :  5


In [23]:
in_arr = [24, 48, 16]
bit_shift =[3, 4, 2]

print ("Input array : ", in_arr)
print ("Number of bit shift : ", bit_shift)

out_arr = np.right_shift(in_arr, bit_shift)
print ("Output array after right shifting: ", out_arr)

Input array :  [24, 48, 16]
Number of bit shift :  [3, 4, 2]
Output array after right shifting:  [3 3 4]


### binary_repr() function

In [24]:
in_num = 10

print ("Input  number : ", in_num)

out_num = np.binary_repr(in_num)
print ("binary representation of 10 : ", out_num)

Input  number :  10
binary representation of 10 :  1010


In [28]:
in_arr = [5, -8 ]
print ("Input array : ", in_arr) 

out_num1 = np.binary_repr(in_arr[0])
out_num2 = np.binary_repr(in_arr[1])
print ("Without using width parameter : ", out_num1, out_num2)

out_num1 = np.binary_repr(in_arr[0], width = 5)
out_num1 = np.binary_repr(in_arr[1], width = 5)
print ("Using width parameter : ", out_num1, out_num2)

Input array :  [5, -8]
Without using width parameter :  101 -1000
Using width parameter :  11000 -1000


### packbits() function

In [29]:
a = np.array([[[1,0,1],
             [0,1,0]],
             [[1,1,0],
             [0,0,1]]])

b = np.packbits(a, axis=-1)
 
print(b)

[[[160]
  [ 64]]

 [[192]
  [ 32]]]


### unpackbits() function

In [30]:
a = np.array([[2], [7], [23]], dtype=np.uint8)

b = np.unpackbits(a, axis = 1)
 
print(b)

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 1 1]]
